apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let’s Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: knetl.j@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account’s private key.
      name: letsencrypt-prod-acc-key
    solvers:
    - http01:
        ingress:
          class: traefik